# DB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_tinyshorturl?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useLocalSessionState=true
    username: root
    password: abc12345
    driver-class-name: com.mysql.cj.jdbc.Driver

# 原始URL
rawurl:
   host: baidu.com
   home: https://www.baidu.com

# 短URL
shorturl:
   protocol: http
   host: localhost:8080
   path: /shorturl