# 环境
spring:
  profiles:
    active: dev

# Web服务器配置
server:
  tomcat:
    accesslog: # 访问日志配置
      directory: ${LOGS_DIR}
      # 默认为 common 即 '%h %l %u %t "%r" %s %b'
      pattern: '%h %l %u %t "%r" %s %b (%D ms)'